version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - converter-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    container_name: service2
    ports:
      - "${SERVICE2_PORT}:8081"
    networks:
      - converter-network
    environment:
      SERVER_PORT: 8081

  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    container_name: service1
    ports:
      - "${SERVICE1_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      
      SERVICE2_BASE_URL: ${SERVICE2_BASE_URL}
      SERVER_PORT: 8080
    networks:
      - converter-network
    depends_on:
      postgres:
        condition: service_healthy
      service2:
        condition: service_started

networks:
  converter-network:
    driver: bridge

volumes:
  pgdata: