spring.application.name=service3

minio.endpoint=${MINIO_ENDPOINT}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET_NAME}

logging.level.root=INFO
logging.level.com.elizaveta.service3=DEBUG
logging.file.name=logs/service3.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{36} | %msg%n
logging.pattern.console=%d{HH:mm:ss} | %-5level | %logger{36} | %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false