spring.application.name=service2

logging.level.root=INFO

logging.level.com.elizaveta.service2=DEBUG

logging.file.name=logs/service2.log

logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{36} | %msg%n

logging.pattern.console=%d{HH:mm:ss} | %-5level | %logger{36} | %msg%n

logging.logback.rollingpolicy.max-file-size=10MB

logging.logback.rollingpolicy.max-history=7

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true